### ISSUE TITLE
Error writing to I2C bus on RP2040

### ISSUE THREAD

**Issue by ARibecaJob** [Sensirion/arduino-i2c-scd30#2]
Hi, 

I'm trying to use a scd30 with an RP2040.
Using the example code, the first readings are ok but after a certain period an endless cycle of i2c error starts:

> firmware version major: 3minor: 66
> co2Concentration: 917.43temperature: 23.24humidity: 39.04
> co2Concentration: 568.79temperature: 23.31humidity: 38.49
> co2Concentration: 590.74temperature: 23.25humidity: 38.36
> co2Concentration: 545.61temperature: 23.08humidity: 38.39
> co2Concentration: 538.20temperature: 23.03humidity: 38.41
> Error trying to execute blockingReadMeasurementData(): Not enough data received
> co2Concentration: 547.65temperature: 22.97humidity: 38.43
> co2Concentration: 585.76temperature: 23.01humidity: 39.75
> co2Concentration: 585.00temperature: 22.95humidity: 38.99
> co2Concentration: 584.00temperature: 22.84humidity: 38.69
> co2Concentration: 576.25temperature: 22.80humidity: 38.67
> co2Concentration: 568.14temperature: 22.80humidity: 38.82
> Error trying to execute blockingReadMeasurementData(): Not enough data received
> co2Concentration: 563.17temperature: 22.76humidity: 39.01
> co2Concentration: 532.14temperature: 22.46humidity: 39.51
> co2Concentration: 532.02temperature: 22.40humidity: 39.57
> Error trying to execute blockingReadMeasurementData(): Not enough data received
> Error trying to execute blockingReadMeasurementData(): Error writing to I2C bus
> Error trying to execute blockingReadMeasurementData(): Error writing to I2C bus
> ...

How can I fix it?

Thank you,

Alessio

**Comment by quentin-cy** [comment]
Hello Alessio,

Thanks for reaching out.
The code from his repo is meant to be used on arduino platforms.
We have [raspi drivers for SCD30](https://github.com/Sensirion/raspberry-pi-i2c-scd30).
We also have [embedded platform  drivers](https://github.com/Sensirion/embedded-i2c-scd30) in case your design does not support floating point.

You should give those drivers a try. You can always open a ticket there if you need help.
I hope it helps.

Cheers
Q

**Comment by ARibecaJob** [comment]
Hi,

I've already tested [raspi drivers](https://github.com/Sensirion/raspberry-pi-i2c-scd30) and, with some efforts 'cause picow is needed some cmake stuff, it works.
I use this driver with [arduino-pico](https://github.com/earlephilhower/arduino-pico). There is probably a bug in this library.

Thank you.
